version: "3.9"
services:
  registry:
    image: quay.io/quarkus/registry-app
    environment:
      - TOKEN=test
      - QUARKUS_DATASOURCE_USERNAME=postgresql
      - QUARKUS_DATASOURCE_PASSWORD=postgresql
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://database:5432/registrydb
      - QUARKUS_REGISTRY_NON_PLATFORM_EXTENSIONS_SUPPORT=false
      - QUARKUS_REGISTRY_ID=registry.quarkus.redhat.com
      - QUARKUS_REGISTRY_QUARKUS_VERSIONS_EXPRESSION=*-redhat-*
      - QUARKUS_REGISTRY_QUARKUS_VERSIONS_EXCLUSIVE_PROVIDER=true
      - QUARKUS_REGISTRY_GROUPID=com.redhat.quarkus.registry
      - QUARKUS_REGISTRY_MAVEN_REPO_URL=https://registry.quarkus.redhat.com/maven
    ports:
      - "8085:8080"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=registrydb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d registrydb -U postgresql"]
      interval: 3s
      timeout: 5s
      retries: 5

  code-quarkus-api:
    image: quay.io/quarkus/code-quarkus-api
    ports:
      - "8080:8080"
    environment:
      - IO_QUARKUS_CODE_QUARKUS_PLATFORMS_REGISTRY_ID=registry.quarkus.redhat.com
      - IO_QUARKUS_CODE_EXTENSION_PROCESSOR_TAGS_FROM=redhat-support
      - QUARKUS_REGISTRIES=registry.quarkus.redhat.com,registry.quarkus.io
      - QUARKUS_REGISTRY_REGISTRY_QUARKUS_REDHAT_COM_REPO_URL=http://registry:8080/maven
      - QUARKUS_REGISTRY_REGISTRY_QUARKUS_IO_REPO_URL=https://registry.quarkus.io/maven
#      - BOOTSTRAP_MAVEN_REPOS=redhat-ga
#      - BOOTSTRAP_MAVEN_REPO_REDHAT_GA_URL=https://maven.repository.redhat.com/ga
      - BOOTSTRAP_MAVEN_REPOS=indy-static
      - BOOTSTRAP_MAVEN_REPO_INDY_STATIC_URL=http://indy.psi.redhat.com/api/content/maven/group/static
    #command: bash -c 'while [[ "$$(curl --connect-timeout 2 -s -o /dev/null -w ''%{http_code}'' http://registry:8080/client/platforms)" != "200" ]]; do echo ..; sleep 5; done; echo backend is up;'
    depends_on:
      - registry

  code-quarkus-frontend:
    image: quay.io/redhat-developer/code-quarkus
    ports:
      - "3000:8082"
    depends_on:
      - code-quarkus-api